### ISSUE TITLE
Better Chat fails to load after latest Trackmania update

### ISSUE THREAD

**Issue by ragraham91** [codecat/tm-better-chat#66]
Better Chat fails to load when starting Trackmania, with the below text left in the Openplanet.log file. This has been happening since the new season Trackmania update.

> [    ScriptEngine] [22:48:39] [BetterChat]  BetterChat.op/:/src/ChatMessageLoop.as (45, 1) : INFO : Compiling void ChatMessageLoop()
> [    ScriptEngine] [22:48:39] [BetterChat]  BetterChat.op/:/src/ChatMessageLoop.as (50, 13) :  ERR : 'ChatHistoryTimestamp' is not a member of 'CGameCtnNetwork'
> [    ScriptEngine] [22:48:39] [BetterChat]  BetterChat.op/:/src/ChatMessageLoop.as (51, 21) :  ERR : 'ChatHistoryTimestamp' is not a member of 'CGameCtnNetwork'
> [    ScriptEngine] [22:48:39] [BetterChat]  BetterChat.op/:/src/ChatMessageLoop.as (57, 31) :  ERR : 'ChatHistoryTimestamp' is not a member of 'CGameCtnNetwork'
> [    ScriptEngine] [22:48:39] [BetterChat]  BetterChat.op/:/src/ChatMessageLoop.as (58, 32) :  ERR : 'ChatHistoryLines' is not a member of 'CGameCtnNetwork'
> [    ScriptEngine] [22:48:39] [BetterChat]  BetterChat.op/:/src/ChatMessageLoop.as (59, 23) :  ERR : 'ChatHistoryTimestamp' is not a member of 'CGameCtnNetwork'
> [    ScriptEngine] [22:48:39] [BetterChat]  BetterChat.op/:/src/ChatMessageLoop.as (72, 13) : WARN : 'time' is not initialized.
> [    ScriptEngine] [22:48:39]  Script compilation failed!

**Comment by codecat** [comment]
I am waiting on Nadeo to make some API changes that will allow to make this work again. Unfortunately I don't have a time schedule for this, but I'll let y'all know how it goes. 👍

**Comment by skybaks** [comment]
I found `cast<CGameManiaPlanet>(GetApp()).ManiaPlanetScriptAPI.ServerChatLog` which appears to be a realtime JSON formatted version of the server's chatlog.
![image](https://github.com/codecat/tm-better-chat/assets/52106022/67cbf128-0cf2-4754-bace-c296d73cd234)
I have only tested in Nadeo room online servers but it appears to work with some amount of hackery.

The largest drawbacks to using this as the chat source would be that you will need to reparse the entire Json string every loop iteration, which seems sadly inefficient and may start to cause performance issues when playing on a server for a long period of time. Also, all the parsing code in ChatLineInfo would need to be reworked to accept a Json::Value instead of a string.

**Comment by codecat** [comment]
Yep, that's the reason why I haven't implemented that json solution yet - it's very inefficient and adds way too much overhead.

**Comment by sullyj3** [comment]
What's the context here, has Nadeo actually made any indication they're going to make the necessary API changes?

**Comment by codecat** [comment]
Yes, I've been told they'll be doing this, but it likely will be next season.

**Comment by LMelaia** [comment]
It’s sucks nadeo’s so slow when the modding community is so fast.

**Comment by codecat** [comment]
Today's game update will make Better Chat work again! I've been working on it today and will hopefully have an update ready soon.

**Comment by recliq** [comment]
This is great news! Thank you for the notice.

**Comment by codecat** [comment]
Unfortunately we have to wait for an update or 2 more for this to really work, as the new API turned out to be incomplete - it's looking promising though. I've pushed some preliminary changes in 700a38b36b79878a479ef707f87e314221fea6dc (won't compile on Openplanet 1.26.0 right now, so this will also require an Openplanet update).

**Comment by sullyj3** [comment]
Bummer, thanks for the update and all your work though!

**Comment by codecat** [comment]
This will still require a game + Openplanet update, but I got it working again!

![image](https://github.com/codecat/tm-better-chat/assets/136534/d9dc599c-160e-4ad6-a847-beace39f147b)

**Comment by ragraham91** [comment]
Great work! Thank you very much.

**Comment by codecat** [comment]
I'm gonna keep this issue open until all the necessary updates are released ☺️

**Comment by codecat** [comment]
The game has been updated, and Better Chat 1.1.0 has been released!

**Comment by recliq** [comment]
Thank you! ❤️

**Comment by ragraham91** [comment]
Fantastic work. Thank you, codecat.
